import FWCore.ParameterSet.Config as cms

cscTimingAnalyzer = cms.EDAnalyzer('CSCTimingAnalyzer',
                                   makeChamberTimingCorrectionValueHists = cms.untracked.bool(False),
                                   makePlotsPerChamber = cms.untracked.bool(False),
                                   makePlotsPerLayer = cms.untracked.bool(False),
                                   printTimeCorrectionParametersToFile = cms.untracked.bool(False),
                                   writeTimeCorrectionParametersToTree = cms.untracked.bool(False),
                                   verbose = cms.untracked.bool(False),
                                   debug = cms.untracked.bool(False),
                                   applyUpdatedME11corrections = cms.untracked.bool(False),
                                   checkCSCstatus = cms.untracked.bool(False),
                                   checkDCSstatus = cms.untracked.bool(False),
                                   removeHeuristicCorrection = cms.untracked.bool(False),
                                   applyNewHeuristicCorrectionByRing = cms.untracked.bool(False),
                                   applyNewHeuristicCorrectionByChamber = cms.untracked.bool(False),
                                   makeNminus1hists = cms.untracked.bool(False),
                                   writeTimingStudyBabyTree = cms.untracked.bool(False),
                                   removeMatchedStationsRequirement = cms.untracked.bool(False),
                                   combineME11ab = cms.untracked.bool(True),
                                   min_pt = cms.untracked.double(10.),
                                   max_dz = cms.untracked.double(0.5),
                                   min_run = cms.untracked.int32(0),
                                   max_run = cms.untracked.int32(999999),
                                   outfileName = cms.untracked.string('histos.root'),
                                   timeParamFileName = cms.untracked.string('cscTimingParameters.root'),
                                   timingStudyBabyFileName = cms.untracked.string('timingBaby.root'),
                                   fpForHeuristicCorrByRing = cms.FileInPath('CSCOfflineTiming/CSCTimingAnalyzer/data/timing_corrections_by_ring_combinedME11ab_2017.txt'),
                                   fpForHeuristicCorrByChamber = cms.FileInPath('CSCOfflineTiming/CSCTimingAnalyzer/data/cscHeurCorr_by_chamber_Oct3.txt'),
)
