use_x509userproxy = true

Initialdir        = RUNDIR_REPLACETAG
log               = logs/job.$(ClusterId).$(ProcId).log
output            = logs/job.$(ClusterId).$(ProcId).out
error             = logs/job.$(ClusterId).$(ProcId).err

+JobFlavour = "tomorrow"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = CMSSWVERSION_REPLACETAG/src/CSCOfflineTiming/CSCTimingAnalyzer/macros/anode_bx_offsets_RUNNUM_REPLACETAG.txt,CMSSWVERSION_REPLACETAG/src/CSCOfflineTiming/CSCTimingAnalyzer/macros/anode_means_and_rms.png,CMSSWVERSION_REPLACETAG/src/CSCOfflineTiming/CSCTimingAnalyzer/macros/anode_time_combined.png,CMSSWVERSION_REPLACETAG/src/CSCOfflineTiming/CSCTimingAnalyzer/macros/cathode_time_combined.png,CMSSWVERSION_REPLACETAG/src/CSCOfflineTiming/CSCTimingAnalyzer/macros/segment_time_combined.png,CMSSWVERSION_REPLACETAG/src/CSCOfflineTiming/CSCTimingAnalyzer/macros/plots/all_plots/RUNNUM_REPLACETAG/removeAnodeCorr
transfer_input_files = ""

request_cpus      = 1
request_memory    = 512M
request_disk      = 1G

executable        = RUNDIR_REPLACETAG/job_baby.sh
arguments         = SCRAMARCH_REPLACETAG CMSSWVERSION_REPLACETAG RUNDIR_REPLACETAG ANADIR_REPLACETAG ANALYZEROUTPUT_REPLACETAG REMOVEHEURISTIC_REPLACETAG RUNNUM_REPLACETAG HEURISTICCORR_REPLACETAG

queue
