# void determineHeuristicCorrections (std::string fname, bool byStation, bool byChamber, bool combineME11ab = false, std::string ofname = "")
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_removeHeuristicCorr.root",false,true,true,"cscHeurCorr_by_chamber_Jul5.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_removeHeuristicCorr.root",true,false,true,"cscHeurCorr_by_ring_Jul5.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_removeHeuristicCorr.root",true,false,true,"cscHeurCorr_by_ring_Jul5.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_removeHeuristicCorr.root",false,true,true,"cscHeurCorr_by_chamber_2016H.txt")'

# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr_297292.root",true,false,true,"cscHeurCorr_by_ring_Jul6.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr_297292.root",false,true,true,"cscHeurCorr_by_chamber_Jul6.txt")'

# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_applyGoodRunList_removeHeuristicCorr.root",false,true,true,"cscHeurCorr_by_chamber_Jul8.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_applyGoodRunList_removeHeuristicCorr.root",true,false,true,"cscHeurCorr_by_ring_Jul8.txt")'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_removeHeuristicCorr.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_removeHeuristicCorr.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_removeHeuristicCorr.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_removeHeuristicCorr.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_removeHeuristicCorr.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_removeHeuristicCorr.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_newHeuristicCorrByChamber.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_newHeuristicCorrByChamber.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_newHeuristicCorrByChamber.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_newHeuristicCorrByChamber.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_newHeuristicCorrByChamber.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_newHeuristicCorrByChamber.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_applyGoodRunList_98.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_applyGoodRunList_98.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_applyGoodRunList_98.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_applyGoodRunList_98.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_applyGoodRunList_98.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/rootfiles/histos_applyGoodRunList_98.root",true)'

# rot dumpPlots.C'("histos_test.root")'
# rot makeMuonTimingPlot.C'("histos_test.root")'
# rot combineRechitTimingDistributions.C'("histos_test.root")'
# rot combineSegmentTimingDistributions.C'("histos_test.root")'
# rot makeMeanTimingPlot.C'("histos_test.root",true)'
# rot makeSegmentMeanTimingPlot.C'("histos_test.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root",true)'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root",false)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root",false)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root",true)'

rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root",false)'
rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root",false)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCtiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root",true)'
