#!/bin/bash
mkdir -p plots

# void determineHeuristicCorrections (std::string fname, bool byStation, bool byChamber, bool combineME11ab = false, std::string ofname = "")
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_removeHeuristicCorr.root",false,true,true,"cscHeurCorr_by_chamber_Jul5.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_removeHeuristicCorr.root",true,false,true,"cscHeurCorr_by_ring_Jul5.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_removeHeuristicCorr.root",true,false,true,"cscHeurCorr_by_ring_Jul5.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_removeHeuristicCorr.root",false,true,true,"cscHeurCorr_by_chamber_2016H.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_2017D.root",false,true,true,"cscHeurCorr_by_chamber_2017D.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_Sep29.root",false,true,true,"cscHeurCorr_by_chamber_Sep29.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_Oct3.root",false,true,true,"cscHeurCorr_by_chamber_Oct3.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_9000_removeHeuristicCorr.root",false,true,true,"cscHeurCorr_by_testZMM.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_rhc_dyjets_92x.root",false,true,true,"cscHeurCorr_by_chamber_92X.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_92x_removeHeuristicCorr.root",false,true,true,"cscHeurCorr_by_chamber_92X.txt")'

# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr_297292.root",true,false,true,"cscHeurCorr_by_ring_Jul6.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr_297292.root",false,true,true,"cscHeurCorr_by_chamber_Jul6.txt")'

# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_applyGoodRunList_removeHeuristicCorr.root",false,true,true,"cscHeurCorr_by_chamber_Jul8.txt")'
# rot determineHeuristicCorrections.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_applyGoodRunList_removeHeuristicCorr.root",true,false,true,"cscHeurCorr_by_ring_Jul8.txt")'

# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_bxshift2.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_bxshift2.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_bxshift2.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_bxshift2.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_bxshift2.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_bxshift2.root",true)'
# rot combineAnodeTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_bxshift2.root")'

rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_mcdbv3.root")'
rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_mcdbv3.root")'
rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_mcdbv3.root")'
rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_mcdbv3.root",true)'
rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_mcdbv3.root",true)'
rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_mcdbv3.root",true)'
rot combineAnodeTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_10_1_0_pre2/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_mcdbv3.root")'

# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_dyjets_92x.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_dyjets_92x.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_dyjets_92x.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_dyjets_92x.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_dyjets_92x.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_dyjets_92x.root",true)'
# rot combineAnodeTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_dyjets_92x.root")'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_removeHeuristicCorr.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_removeHeuristicCorr.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_removeHeuristicCorr.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_removeHeuristicCorr.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_removeHeuristicCorr.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_removeHeuristicCorr.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_newHeuristicCorrByChamber.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_newHeuristicCorrByChamber.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_newHeuristicCorrByChamber.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_newHeuristicCorrByChamber.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_newHeuristicCorrByChamber.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_newHeuristicCorrByChamber.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_applyGoodRunList_98.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_applyGoodRunList_98.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_applyGoodRunList_98.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_applyGoodRunList_98.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_applyGoodRunList_98.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_applyGoodRunList_98.root",true)'

# rot dumpPlots.C'("histos_test.root")'
# rot makeMuonTimingPlot.C'("histos_test.root")'
# rot combineRechitTimingDistributions.C'("histos_test.root")'
# rot combineSegmentTimingDistributions.C'("histos_test.root")'
# rot makeMeanTimingPlot.C'("histos_test.root",true)'
# rot makeSegmentMeanTimingPlot.C'("histos_test.root",true)'

# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root", true)'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root", true)'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root", true)'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root",true, true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root",true, true)'

# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco299649.root",true)'

# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_Oct16.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_Oct16.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_Oct16.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_Oct16.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_Oct16.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_Oct16.root",true)'
# rot combineAnodeTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_Oct16.root")'

# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newBXOffset.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newBXOffset.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newBXOffset.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newBXOffset.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newBXOffset.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newBXOffset.root",true)'

# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_fg2016.root",true)'

# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_3_1/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_testCorrectWireTime_newHeuristicCor# rByChamber.root",true)'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_3_1/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_testCorrectWireTime_newHeuristicCorrByChamber.root")'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_3_1/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_testCorrectWireTime_newHeuristicCorrByChamber.root",true)'

# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_2017D.root",true)'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_2017D.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_2017D.root",true)'

# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_2017Cv1.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_2017Cv2.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_2017Cv3.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_2017Bv1.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_2017Bv2.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/rootfiles/histos_agr_rhc_Oct3.root",true)'

# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_3_1/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_Oct3.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_3_1/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_Oct3.root",true)'
# rot makeAnodeTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_3_1/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_Oct3.root",true)'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_3_1/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_Oct3.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_3_1/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_Oct3.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_3_1/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_Oct3.root")'
# rot combineAnodeTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_3_1/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_Oct3.root")'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newAnodeOffset.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newAnodeOffset.root", true)'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newAnodeOffset.root", true)'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newAnodeOffset.root", true)'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newAnodeOffset.root",true, true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newAnodeOffset.root",true, true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root",true)'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root",false)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList.root",false)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_removeHeuristicCorr.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_applyGoodRunList_newHeuristicCorrByChamber.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_newHeuristicCorrByChamber.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root",true)'

# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root",false)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_rereco.root",false)'

# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_testC_newHeuristicCorrByChamber.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_testC_newHeuristicCorrByChamber.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_testC_newHeuristicCorrByChamber.root",true)'

# rot dumpPlots.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root")'
# rot makeMuonTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root")'
# rot combineRechitTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root")'
# rot combineSegmentTimingDistributions.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root")'
# rot makeMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root",true)'
# rot makeSegmentMeanTimingPlot.C'("/home/users/sicheng/working/CSCTiming/CMSSW_9_2_4/src/CSCOfflineTiming/CSCTimingAnalyzer/test/histos_barereco.root",true)'
